#!/usr/bin/env python3
"""Evaluator-sensitivity comparison for Codex GPT-5.5 vs gpt-4.1-mini.

This is a methodology-validation script. It uses the canonical Lu-style
role-specific eval_prompt fields from data/roles/instructions/{role}.json.

Implementation note: Codex GPT-5.5 is not callable from Python in this local
environment. The Codex side of the comparison is therefore imported from the
existing audited Codex score JSONL files. The gpt-4.1-mini side is generated by
this script over the exact same response records and parsed with the same
integer parser used for all API judge outputs.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import time
import urllib.error
import urllib.request
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[4]
OUT_DIR = ROOT / "research/q2_stability/qwen/evaluator_sensitivity"
RESULTS_JSONL = OUT_DIR / "evaluator_sensitivity_results.jsonl"
SUMMARY_JSON = OUT_DIR / "evaluator_sensitivity_summary.json"
REPORT_MD = OUT_DIR / "evaluator_sensitivity_analysis.md"
INTERPRETATION_MD = OUT_DIR / "evaluator_sensitivity_interpretation.md"
EDITOR_CONFUSION = OUT_DIR / "editor_confusion_matrix.csv"
TRICKSTER_CONFUSION = OUT_DIR / "trickster_confusion_matrix.csv"

EXTRACTION_QUESTIONS = ROOT / "data/extraction_questions.jsonl"
ROLE_INSTRUCTIONS = ROOT / "data/roles/instructions"

CORPORA = {
    "trickster": {
        "responses": ROOT / "research/q2_stability/qwen/outputs/paper1_5/trickster_phase1.jsonl",
        "codex_scores": ROOT
        / "research/q2_stability/qwen/outputs/paper1_5/trickster_phase2_scores_codex_gpt55.jsonl",
        "codex_summary": ROOT
        / "research/q2_stability/qwen/outputs/paper1_5/trickster_phase2_scores_codex_gpt55_summary.json",
    },
    "editor": {
        "responses": ROOT
        / "research/q2_stability/qwen/outputs/paper1_5/editor/editor_phase1_128.jsonl",
        "codex_scores": ROOT
        / "research/q2_stability/qwen/outputs/paper1_5/editor/editor_phase2_scores_codex_gpt55.jsonl",
        "codex_summary": ROOT
        / "research/q2_stability/qwen/outputs/paper1_5/editor/editor_phase2_scores_codex_gpt55_summary.json",
    },
}


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows = []
    with path.open() as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def append_jsonl(path: Path, row: dict[str, Any]) -> None:
    with path.open("a") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")
        f.flush()


def load_questions() -> dict[int, str]:
    questions = {}
    for idx, row in enumerate(load_jsonl(EXTRACTION_QUESTIONS)):
        questions[idx] = row["question"]
    return questions


def load_eval_prompt(role: str) -> str:
    data = json.loads((ROLE_INSTRUCTIONS / f"{role}.json").read_text())
    return data["eval_prompt"]


def parse_score(text: str) -> int | None:
    m = re.search(r"\b([0-3])\b", text.strip())
    return int(m.group(1)) if m else None


def existing_results() -> dict[tuple[str, int, int, str], dict[str, Any]]:
    if not RESULTS_JSONL.exists():
        return {}
    out = {}
    for row in load_jsonl(RESULTS_JSONL):
        key = (row["role"], int(row["sp_idx"]), int(row["q_idx"]), row["evaluator"])
        out[key] = row
    return out


def canonical_records() -> list[dict[str, Any]]:
    questions = load_questions()
    records = []
    for role, paths in CORPORA.items():
        responses = {
            (int(row["sp_idx"]), int(row["q_idx"])): row
            for row in load_jsonl(paths["responses"])
        }
        for score_row in load_jsonl(paths["codex_scores"]):
            sp_idx = int(score_row["sp_idx"])
            q_idx = int(score_row["q_idx"])
            response = responses[(sp_idx, q_idx)]
            records.append(
                {
                    "role": role,
                    "sp_idx": sp_idx,
                    "q_idx": q_idx,
                    "question": questions[q_idx],
                    "response_text": response["response_text"],
                    "truncated": bool(response.get("truncated", False)),
                    "response_length_chars": len(response.get("response_text", "")),
                    "generation_model": response.get("generation_model", ""),
                    "script_author_model": response.get("script_author_model", ""),
                    "codex_score": int(score_row["score"]),
                    "codex_rationale": score_row.get("rationale", ""),
                    "codex_source_path": str(paths["codex_scores"].relative_to(ROOT)),
                    "response_source_path": str(paths["responses"].relative_to(ROOT)),
                }
            )
    return records


def import_codex_scores(records: list[dict[str, Any]], seen: dict) -> None:
    for rec in records:
        key = (rec["role"], rec["sp_idx"], rec["q_idx"], "Codex GPT-5.5 Standard")
        if key in seen:
            continue
        row = {
            "role": rec["role"],
            "sp_idx": rec["sp_idx"],
            "q_idx": rec["q_idx"],
            "question": rec["question"],
            "evaluator": "Codex GPT-5.5 Standard",
            "evaluator_source": "imported_existing_codex_scores",
            "judge_prompt_source": "existing Codex score file; prior scoring rubric, not callable from Python",
            "score": rec["codex_score"],
            "raw_output": str(rec["codex_score"]),
            "parse_ok": True,
            "rationale": rec["codex_rationale"],
            "truncated": rec["truncated"],
            "response_length_chars": rec["response_length_chars"],
            "generation_model": rec["generation_model"],
            "script_author_model": rec["script_author_model"],
            "response_text": rec["response_text"],
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        append_jsonl(RESULTS_JSONL, row)
        seen[key] = row


def get_api_key() -> str:
    if os.environ.get("OPENAI_API_KEY"):
        return os.environ["OPENAI_API_KEY"]
    token_path = Path.home() / ".openai_api_key"
    if token_path.exists():
        return token_path.read_text().strip()
    raise RuntimeError("OPENAI_API_KEY is not set and ~/.openai_api_key does not exist")


def call_openai_responses(prompt: str, model: str, temperature: float = 0.0) -> str:
    api_key = get_api_key()
    payload = {
        "model": model,
        "input": prompt,
        "temperature": temperature,
        "max_output_tokens": 16,
    }
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        "https://api.openai.com/v1/responses",
        data=data,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=90) as resp:
        body = json.loads(resp.read().decode("utf-8"))
    if "output_text" in body:
        return body["output_text"]
    chunks = []
    for item in body.get("output", []):
        for content in item.get("content", []):
            if content.get("type") in {"output_text", "text"}:
                chunks.append(content.get("text", ""))
    return "".join(chunks)


def score_gpt41mini(records: list[dict[str, Any]], seen: dict, limit: int | None = None) -> None:
    completed = 0
    for rec in records:
        key = (rec["role"], rec["sp_idx"], rec["q_idx"], "gpt-4.1-mini")
        if key in seen:
            continue
        eval_prompt = load_eval_prompt(rec["role"])
        prompt = eval_prompt.format(question=rec["question"], answer=rec["response_text"])
        attempts = 0
        while True:
            attempts += 1
            try:
                raw = call_openai_responses(prompt, "gpt-4.1-mini", temperature=0.0)
                break
            except urllib.error.HTTPError as e:
                body = e.read().decode("utf-8", errors="replace")
                if attempts >= 4:
                    raise RuntimeError(f"OpenAI HTTPError after {attempts} attempts: {e.code} {body}") from e
                time.sleep(min(20, attempts * 3))
            except Exception:
                if attempts >= 4:
                    raise
                time.sleep(min(20, attempts * 3))
        parsed = parse_score(raw)
        row = {
            "role": rec["role"],
            "sp_idx": rec["sp_idx"],
            "q_idx": rec["q_idx"],
            "question": rec["question"],
            "evaluator": "gpt-4.1-mini",
            "evaluator_source": "openai_responses_api",
            "judge_prompt_source": f"data/roles/instructions/{rec['role']}.json eval_prompt",
            "score": parsed,
            "raw_output": raw,
            "parse_ok": parsed is not None,
            "rationale": "",
            "truncated": rec["truncated"],
            "response_length_chars": rec["response_length_chars"],
            "generation_model": rec["generation_model"],
            "script_author_model": rec["script_author_model"],
            "response_text": rec["response_text"],
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        append_jsonl(RESULTS_JSONL, row)
        seen[key] = row
        completed += 1
        if completed % 10 == 0:
            print(f"gpt-4.1-mini scored {completed} new records")
        if limit is not None and completed >= limit:
            break


def score_distribution(rows: list[dict[str, Any]]) -> dict[str, Any]:
    counts = Counter(int(row["score"]) for row in rows if row.get("score") is not None)
    total = sum(counts.values())
    return {
        str(i): {"count": counts[i], "fraction": counts[i] / total if total else 0.0}
        for i in range(4)
    }


def confusion(pairs: list[tuple[int, int]]) -> list[list[int]]:
    mat = [[0 for _ in range(4)] for _ in range(4)]
    for a, b in pairs:
        mat[a][b] += 1
    return mat


def cohen_kappa(pairs: list[tuple[int, int]]) -> float:
    if not pairs:
        return 0.0
    mat = confusion(pairs)
    n = sum(sum(row) for row in mat)
    po = sum(mat[i][i] for i in range(4)) / n
    row_totals = [sum(row) for row in mat]
    col_totals = [sum(mat[i][j] for i in range(4)) for j in range(4)]
    pe = sum(row_totals[i] * col_totals[i] for i in range(4)) / (n * n)
    return (po - pe) / (1 - pe) if pe != 1 else 0.0


def write_confusion_csv(path: Path, mat: list[list[int]]) -> None:
    with path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["codex_gpt55\\gpt41mini", "0", "1", "2", "3"])
        for i, row in enumerate(mat):
            writer.writerow([i] + row)


def summarize() -> dict[str, Any]:
    rows = load_jsonl(RESULTS_JSONL)
    by_key = {(r["role"], int(r["sp_idx"]), int(r["q_idx"]), r["evaluator"]): r for r in rows}
    roles = sorted({r["role"] for r in rows})
    role_summaries = {}
    all_pairs = []
    for role in roles:
        codex = [
            r
            for r in rows
            if r["role"] == role and r["evaluator"] == "Codex GPT-5.5 Standard"
        ]
        gpt = [r for r in rows if r["role"] == role and r["evaluator"] == "gpt-4.1-mini"]
        pairs = []
        shifts = []
        for c in codex:
            g = by_key.get((role, int(c["sp_idx"]), int(c["q_idx"]), "gpt-4.1-mini"))
            if g is None or g.get("score") is None:
                continue
            pair = (int(c["score"]), int(g["score"]))
            pairs.append(pair)
            all_pairs.append(pair)
            shifts.append(pair[1] - pair[0])
        exact = sum(1 for a, b in pairs if a == b)
        ge2_same = sum(1 for a, b in pairs if (a >= 2) == (b >= 2))
        eq3_same = sum(1 for a, b in pairs if (a == 3) == (b == 3))
        role_summaries[role] = {
            "n_codex": len(codex),
            "n_gpt41mini": len(gpt),
            "n_pairs": len(pairs),
            "codex_distribution": score_distribution(codex),
            "gpt41mini_distribution": score_distribution(gpt),
            "codex_score_ge_2": sum(1 for r in codex if int(r["score"]) >= 2),
            "gpt41mini_score_ge_2": sum(1 for r in gpt if r.get("score") is not None and int(r["score"]) >= 2),
            "codex_score_eq_3": sum(1 for r in codex if int(r["score"]) == 3),
            "gpt41mini_score_eq_3": sum(1 for r in gpt if r.get("score") is not None and int(r["score"]) == 3),
            "exact_agreement": exact / len(pairs) if pairs else 0.0,
            "score_ge_2_agreement": ge2_same / len(pairs) if pairs else 0.0,
            "score_eq_3_agreement": eq3_same / len(pairs) if pairs else 0.0,
            "cohen_kappa": cohen_kappa(pairs),
            "confusion_matrix_codex_rows_gpt41mini_cols": confusion(pairs),
            "mean_score_shift_gpt41mini_minus_codex": sum(shifts) / len(shifts) if shifts else 0.0,
            "shift_counts": dict(Counter(shifts)),
            "thresholds": {
                "codex_ge2_meets_64": sum(1 for r in codex if int(r["score"]) >= 2) >= 64,
                "gpt41mini_ge2_meets_64": sum(1 for r in gpt if r.get("score") is not None and int(r["score"]) >= 2) >= 64,
                "codex_eq3_meets_16": sum(1 for r in codex if int(r["score"]) == 3) >= 16,
                "gpt41mini_eq3_meets_16": sum(1 for r in gpt if r.get("score") is not None and int(r["score"]) == 3) >= 16,
            },
        }
    overall = {
        "n_pairs": len(all_pairs),
        "exact_agreement": sum(1 for a, b in all_pairs if a == b) / len(all_pairs) if all_pairs else 0.0,
        "score_ge_2_agreement": sum(1 for a, b in all_pairs if (a >= 2) == (b >= 2)) / len(all_pairs) if all_pairs else 0.0,
        "score_eq_3_agreement": sum(1 for a, b in all_pairs if (a == 3) == (b == 3)) / len(all_pairs) if all_pairs else 0.0,
        "cohen_kappa": cohen_kappa(all_pairs),
        "confusion_matrix_codex_rows_gpt41mini_cols": confusion(all_pairs),
    }
    return {
        "date": "2026-05-27",
        "model_used": "GPT-5.5",
        "method": "existing_codex_scores_vs_gpt41mini_canonical_eval_prompt_rescore",
        "canonical_judge_prompt_source": "data/roles/instructions/{role}.json eval_prompt; exported at research/assistant_axis_methodology/prompts_and_questions/canonical_judge_prompt.md",
        "important_limitation": "Codex GPT-5.5 is not callable from Python; Codex scores are imported from existing audited score files, while gpt-4.1-mini is newly scored with canonical Lu eval prompts.",
        "corpora": {
            role: {
                "responses": str(paths["responses"].relative_to(ROOT)),
                "codex_scores": str(paths["codex_scores"].relative_to(ROOT)),
                "codex_summary": str(paths["codex_summary"].relative_to(ROOT)),
            }
            for role, paths in CORPORA.items()
        },
        "overall": overall,
        "roles": role_summaries,
    }


def write_report(summary: dict[str, Any]) -> None:
    has_pairs = summary["overall"]["n_pairs"] > 0
    lines = [
        "# Evaluator Sensitivity Analysis",
        "",
        "## Research Question",
        "",
        "How sensitive are role-expression judgments to evaluator model choice when comparing Codex GPT-5.5 Standard and `gpt-4.1-mini` on the same Qwen trickster and editor response corpora?",
        "",
        "## Canonical Judge Materials",
        "",
        "The `gpt-4.1-mini` rescoring uses the canonical role-specific `eval_prompt` fields from `data/roles/instructions/{role}.json`, exported in `research/assistant_axis_methodology/prompts_and_questions/canonical_judge_prompt.md`. These prompts define scores 0-3 and instruct the judge to return only a number.",
        "",
        "## Important Limitation",
        "",
        summary["important_limitation"],
        "",
        "This means the comparison is controlled on response corpus and parsing, and canonical on the `gpt-4.1-mini` side. It is not a perfect same-prompt re-run of Codex because Codex cannot be invoked programmatically from the local script.",
        "",
        "## Overall Metrics",
        "",
        f"- Paired records: {summary['overall']['n_pairs']}",
    ]
    if has_pairs:
        lines.extend(
            [
                f"- Exact score agreement: {summary['overall']['exact_agreement']:.3f}",
                f"- score>=2 classification agreement: {summary['overall']['score_ge_2_agreement']:.3f}",
                f"- score==3 classification agreement: {summary['overall']['score_eq_3_agreement']:.3f}",
                f"- Cohen's kappa: {summary['overall']['cohen_kappa']:.3f}",
                "",
                "## Per-Role Results",
                "",
                "| Role | n | Codex score>=2 | gpt-4.1-mini score>=2 | Codex score==3 | gpt-4.1-mini score==3 | Exact agreement | ge2 agreement | eq3 agreement | Kappa | Mean shift |",
                "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
            ]
        )
    else:
        lines.extend(
            [
                "- Agreement metrics: not computed because no `gpt-4.1-mini` paired scores were produced.",
                "- API status: the attempted `gpt-4.1-mini` call returned OpenAI `insufficient_quota`; the script preserved the Codex-side baseline and stopped without fabricating scores.",
                "",
                "## Canonical Corpora Located",
                "",
            ]
        )
        for role, paths in summary["corpora"].items():
            lines.append(f"- `{role}` responses: `{paths['responses']}`")
            lines.append(f"- `{role}` Codex scores: `{paths['codex_scores']}`")
        lines.extend(
            [
                "",
                "## Per-Role Baseline Inventory",
                "",
                "| Role | Codex scored | Codex score>=2 | Codex score==3 | gpt-4.1-mini scored | Status |",
                "|---|---:|---:|---:|---:|---|",
            ]
        )
        for role, row in summary["roles"].items():
            lines.append(
                f"| `{role}` | {row['n_codex']} | {row['codex_score_ge_2']} | {row['codex_score_eq_3']} | {row['n_gpt41mini']} | blocked by API quota |"
            )
        lines.extend(
            [
                "",
                "## Interpretation",
                "",
                "The evaluator-sensitivity experiment is not complete. The reproducible harness, canonical corpora selection, Codex baseline import, and output schema are in place, but `gpt-4.1-mini` scoring could not run because the OpenAI API returned `insufficient_quota`.",
                "",
                "No claim should be made about evaluator sensitivity, editor ambiguity, or trickster/editor threshold robustness until `gpt-4.1-mini` scores are successfully generated for the paired records.",
            ]
        )
        REPORT_MD.write_text("\n".join(lines) + "\n")
        INTERPRETATION_MD.write_text(
            "# Evaluator Sensitivity Interpretation\n\n"
            "The evaluator-sensitivity comparison is blocked, not completed. The local script imported 192 existing Codex GPT-5.5 Standard scores across trickster and editor, but the attempted `gpt-4.1-mini` canonical-rubric rescore failed with OpenAI `insufficient_quota`, leaving zero paired evaluator records.\n\n"
            "Current usable state: the harness, canonical prompt path, response-corpus mapping, Codex-side baseline, summary schema, and confusion-matrix outputs are prepared. Next step is to rerun `python3 research/q2_stability/qwen/scripts/evaluator_sensitivity_analysis.py` after API quota is restored. Until then, no conclusion should be drawn about evaluator sensitivity or whether judge substitution contributed to editor extraction failure.\n"
        )
        return
    for role, row in summary["roles"].items():
        lines.append(
            f"| `{role}` | {row['n_pairs']} | {row['codex_score_ge_2']} | {row['gpt41mini_score_ge_2']} | {row['codex_score_eq_3']} | {row['gpt41mini_score_eq_3']} | {row['exact_agreement']:.3f} | {row['score_ge_2_agreement']:.3f} | {row['score_eq_3_agreement']:.3f} | {row['cohen_kappa']:.3f} | {row['mean_score_shift_gpt41mini_minus_codex']:.3f} |"
        )
    lines.extend(
        [
            "",
            "## Threshold Effects",
            "",
        ]
    )
    for role, row in summary["roles"].items():
        th = row["thresholds"]
        lines.append(
            f"- `{role}`: Codex ge2>=64={th['codex_ge2_meets_64']}, gpt-4.1-mini ge2>=64={th['gpt41mini_ge2_meets_64']}; Codex score3>=16={th['codex_eq3_meets_16']}, gpt-4.1-mini score3>=16={th['gpt41mini_eq3_meets_16']}."
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "Evaluator sensitivity should be interpreted role by role. Trickster is the high-separability case: if both evaluators keep nearly all responses at score>=2, adaptive extraction remains robust even if score-3 counts shift. Editor is the low-separability assistant-adjacent case: if both evaluators keep score>=2 far below 64, evaluator substitution does not materially explain the editor extraction failure.",
            "",
            "Do not interpret this comparison as identifying one evaluator as objectively correct. It tests whether extraction-relevant thresholds change under evaluator substitution.",
        ]
    )
    REPORT_MD.write_text("\n".join(lines) + "\n")

    interp = [
        "# Evaluator Sensitivity Interpretation",
        "",
        "This analysis compares existing Codex GPT-5.5 Standard scores against new `gpt-4.1-mini` scores on the same trickster and editor response records. The `gpt-4.1-mini` side uses the canonical Lu-style role-specific `eval_prompt`; the Codex side is imported from existing audited local scoring because Codex is not programmatically callable from Python.",
        "",
    ]
    for role, row in summary["roles"].items():
        interp.append(
            f"For `{role}`, Codex produced {row['codex_score_ge_2']} score>=2 and {row['codex_score_eq_3']} score==3 responses, while `gpt-4.1-mini` produced {row['gpt41mini_score_ge_2']} score>=2 and {row['gpt41mini_score_eq_3']} score==3 responses across {row['n_pairs']} paired records. Exact agreement was {row['exact_agreement']:.3f}, score>=2 agreement was {row['score_ge_2_agreement']:.3f}, and kappa was {row['cohen_kappa']:.3f}."
        )
    interp.extend(
        [
            "",
            "The main methodological question is threshold robustness, not which judge is correct. If trickster remains above adaptive extraction thresholds while editor remains far below them, evaluator substitution is not sufficient to explain the contrast between trickster success and editor failure. If score-3 counts change substantially while score>=2 counts remain stable, future adaptive extraction should treat score>=2 as the more robust operational filter and reserve score==3 for sensitivity analysis.",
        ]
    )
    INTERPRETATION_MD.write_text("\n".join(interp) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit-api", type=int, default=None)
    parser.add_argument("--summarize-only", action="store_true")
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    records = canonical_records()
    seen = existing_results()
    if not args.summarize_only:
        import_codex_scores(records, seen)
        score_gpt41mini(records, seen, limit=args.limit_api)
    summary = summarize()
    SUMMARY_JSON.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    if "editor" in summary["roles"]:
        write_confusion_csv(
            EDITOR_CONFUSION,
            summary["roles"]["editor"]["confusion_matrix_codex_rows_gpt41mini_cols"],
        )
    if "trickster" in summary["roles"]:
        write_confusion_csv(
            TRICKSTER_CONFUSION,
            summary["roles"]["trickster"]["confusion_matrix_codex_rows_gpt41mini_cols"],
        )
    write_report(summary)
    print(f"Wrote {RESULTS_JSONL.relative_to(ROOT)}")
    print(f"Wrote {SUMMARY_JSON.relative_to(ROOT)}")
    print(f"Wrote {REPORT_MD.relative_to(ROOT)}")
    print(f"Wrote {INTERPRETATION_MD.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
