#!/usr/bin/env python3
"""Join Qwen role geometry to the five positive role instructions."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd


REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "research" / "outputs" / "role_geometry_instruction_inventory"
GEOMETRY = REPO / "research" / "geometry_tables" / "qwen_role_pc_rankings.csv"
INSTRUCTION_DIR = REPO / "data" / "roles" / "instructions"


def load_positive_instructions(role: str) -> tuple[list[str], str]:
    path = INSTRUCTION_DIR / f"{role}.json"
    if not path.exists():
        return [], str(path.relative_to(REPO))
    data = json.loads(path.read_text(encoding="utf-8"))
    instructions: list[str] = []
    for item in data.get("instruction", []):
        if isinstance(item, dict) and "pos" in item:
            instructions.append(str(item["pos"]))
    return instructions, str(path.relative_to(REPO))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    geometry = pd.read_csv(GEOMETRY)
    rows = []
    for _, role_row in geometry.sort_values("role").iterrows():
        role = role_row["role"]
        instructions, source = load_positive_instructions(role)
        row = role_row.to_dict()
        row["instruction_source_file"] = source
        row["positive_instruction_count"] = len(instructions)
        for i in range(5):
            row[f"positive_instruction_{i + 1}"] = instructions[i] if i < len(instructions) else ""
        rows.append(row)

    out = pd.DataFrame(rows)
    csv_path = OUT / "qwen_role_geometry_with_positive_instructions.csv"
    out.to_csv(csv_path, index=False)

    missing = out[out["positive_instruction_count"].ne(5)][
        ["role", "positive_instruction_count", "instruction_source_file"]
    ]
    missing.to_csv(OUT / "roles_missing_five_positive_instructions.csv", index=False)

    inventory = pd.DataFrame(
        [
            {
                "artifact": "qwen_role_geometry_with_positive_instructions.csv",
                "path": str(csv_path.relative_to(REPO)),
                "description": "Excel-friendly one-row-per-role table joining Qwen PC geometry to the five positive role-instruction prompts.",
                "status": "active",
            },
            {
                "artifact": "roles_missing_five_positive_instructions.csv",
                "path": str((OUT / "roles_missing_five_positive_instructions.csv").relative_to(REPO)),
                "description": "Rows with fewer or more than five positive role instructions; expected to be empty.",
                "status": "active",
            },
            {
                "artifact": "role_geometry_instruction_inventory_report.md",
                "path": str((OUT / "role_geometry_instruction_inventory_report.md").relative_to(REPO)),
                "description": "Short provenance note for the joined role geometry/instruction table.",
                "status": "active",
            },
            {
                "artifact": "run_role_geometry_instruction_inventory.py",
                "path": str((OUT / "run_role_geometry_instruction_inventory.py").relative_to(REPO)),
                "description": "Generation script.",
                "status": "active",
            },
        ]
    )
    inventory.to_csv(OUT / "artifact_inventory.csv", index=False)

    report = f"""# Role Geometry With Positive Instructions

This directory contains an Excel-friendly CSV that joins each Qwen role/persona centroid to the five positive role-instruction prompts used before the shared extraction questions.

## Output

- `qwen_role_geometry_with_positive_instructions.csv`

## Sources

- Geometry source: `{GEOMETRY.relative_to(REPO)}`
- Instruction source directory: `{INSTRUCTION_DIR.relative_to(REPO)}/`
- Generated by: `run_role_geometry_instruction_inventory.py`
- `model_used`: GPT-5.5 for script/report generation; no model APIs, generation, activation extraction, or projection reruns were performed.

## Contents

- Rows: {len(out)}
- Roles with exactly five positive instructions: {int(out['positive_instruction_count'].eq(5).sum())}
- Roles with non-five positive instruction counts: {len(missing)}

The five instruction columns are named `positive_instruction_1` through `positive_instruction_5`. These are the role-conditioning prompts from the Assistant Axis role artifacts, not the 240 shared extraction questions.

## Caveat

Use this table for source inspection and hypothesis generation. Peculiar wording in the five role instructions can suggest possible causes of outlying role geometry, but it does not by itself establish causality.
"""
    (OUT / "role_geometry_instruction_inventory_report.md").write_text(report, encoding="utf-8")


if __name__ == "__main__":
    main()
